sudo: required
dist: trusty

language: node_js
node_js: 6
    
script:
  - yarn run haxe --cwd tests run.hxml --run Run node
  # - yarn run haxe --cwd tests run.hxml --run Run cs # TODO: install the c# environment
