sudo: required
dist: trusty

language: node_js
node_js: 6
    
install:
  - yarn
  - export PATH=$PATH:$(yarn bin)
  - lix download
  
script:
  - travix node && haxe --cwd tests run.hxml --run Run node
  - travix cs && haxe --cwd tests run.hxml --run Run cs
